# -*- coding: utf-8 -*-
"""OpenAI_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173Wi9nfgVuuNAlnZ3836IcGclJbrIGp5
"""

!pip install openai -q
import openai

from openai import OpenAI

client = OpenAI(
    api_key='your_API_Key'
)

def chat(user_input):
    """
    Sends a chat message to the GPT-4o model and returns its response.

    Args:
        user_input: The user's message to the chatbot.

    Returns:
        The GPT-4o model's response to the user's message.
    """
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": user_input
                    }
                ]
            },
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text":
"You are a python programmer, respond to all coding questions with python scripts"
                    }
                ]
            }
        ],
        temperature=1,
        max_tokens=256,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
        response_format={
            "type": "text"
        }
    )
    return response.choices[0].message.content

# Loop to keep the conversation going
while True:
    # Get user input from the Colab environment
    user_input = input("You: ")

    # Exit the loop if the user types 'exit'
    if user_input.lower() in ['exit', 'quit', 'bye']:
        print("Assistant: Goodbye!")
        break

    # Send the user input to the chat function and print the response
    response = chat(user_input)
    print("Assistant:", response)
